name    'leonardothibes-crontab'
author  'leonardothibes'
version '1.0.0'
license 'MIT'
summary 'A puppet module to manage crontab'
description 'A puppet module to manage crontab'
source 'git://github.com/leonardothibes/puppet-crontab.git'
project_page 'http://github.com/leonardothibes/puppet-crontab'
